credentials        = "./terraform-ca-key.json"
project_id          = "poetic-orb-273115"
region             = "europe-west4"
zones              = ["europe-west4-a", "europe-west4-b", "europe-west4-c"]
name               = "gke-cluster"
machine_type       = "g1-small"
min_count          = 1
max_count          = 3
disk_size_gb       = 10
service_account    = "terraform@poetic-orb-273115.iam.gserviceaccount.com"
initial_node_count = 3
